package io.cursedfunction.runner1

internal fun buildPrintList(): List<String> {
    return listOf(
        "Atlantic Coast Conference - ACC",
        "Schools",
        "---------------------------",
        "1. Boston College - BC - Boston College Eagles",
        "2. University of California-Berkeley - CAL - Cal Golden Bears",
        "3. Clemson University - CLEM - Clemson Tigers",
        "4. Duke University - DUKE - Duke Blue Devils",
        "5. Florida State University - FSU - Florida State Seminoles",
        "6. Georgia Institute of Technology - GT - Georgia Tech Yellow Jackets",
        "7. University of Louisville - LOU - Louisville Cardinals",
        "8. University of Miami - UM - Miami Hurricanes",
        "9. University of North Carolina - UNC - North Carolina Tar Heels",
        "10. North Carolina State University - NCST - North Carolina State Wolfpack",
        "11. University of Pittsburgh - PITT - Pittsburgh Panthers",
        "12. Southern Methodist University - SMU - SMU Mustangs",
        "13. Stanford University - STAN - Stanford Cardinals",
        "14. University of Virginia - UVA - Virginia Cavaliers",
        "15. Virginia Polytechnic Institute and State University - VT - Virginia Tech Hokies",
        "16. Wake Forest University - WF - Wake Forest Demon Deacons",
        "---------------------------",
        "URL: https://theacc.com/sports/football",
        "",
        "South Eastern Conference - SEC",
        "Schools",
        "---------------------------",
        "1. University of Alabama - BAMA - Alabama Crimson Tide",
        "2. University of Arkansas - ARK - Arkansas Razorbacks",
        "3. Auburn University - AUB - Auburn Tigers",
        "4. University of Florida - UF - Florida Gators",
        "5. University of Georgia - UGA - Georgia Bulldogs",
        "6. University of Kentucky - UK - Kentucky Wildcats",
        "7. Louisiana State University - LSU - LSU Tigers",
        "8. University of Mississippi - MISS - Ol Miss Rebels",
        "9. Mississippi State University - MSST - Mississippi State Bulldogs",
        "10. University of Missouri - MIZZ - Missouri Tigers",
        "11. University of Oklahoma - OU - Oklahoma Sooners",
        "12. University of South Carolina - SCAR - South Carolina Gamecocks",
        "13. University of Tennessee - TENN - Tennessee Vols",
        "14. University of Texas - TEX - Texas Longhorns",
        "15. Texas A&M University - TAMU - Texas A&M Aggies",
        "16. Vanderbilt University - VAN - Vanderbilt Commodores",
        "---------------------------",
    )
}
